# 服务启动端口
server:
port: 8080

## 数据源配置
spring:
  datasource:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
